// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240120210504_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Data.Entities.PostEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Author 1",
                            Comment = "Comment 1",
                            Content = "Serious Post",
                            PublicationDate = new DateTime(2024, 1, 20, 22, 5, 4, 170, DateTimeKind.Local).AddTicks(6625),
                            Tags = "Tag1"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Author 2",
                            Comment = "Comment 2",
                            Content = "Less Serious Post",
                            PublicationDate = new DateTime(2024, 1, 20, 22, 5, 4, 170, DateTimeKind.Local).AddTicks(6673),
                            Tags = "Tag2"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Author 3",
                            Comment = "Comment 3",
                            Content = "Not Serious Post",
                            PublicationDate = new DateTime(2024, 1, 20, 22, 5, 4, 170, DateTimeKind.Local).AddTicks(6677),
                            Tags = "Tag3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
